import os
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings
import json, requests, time, docker

import couchdb.couch as couch

class Command(BaseCommand):
    help = 'Initialise the views of each database'

    sports =  {'_id': '_design/sports',
 'views': {'wrestling': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('wrestling'))\n   {emit(doc._id, 1); }\n}",},
  'weights': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('weights'))\n   {emit(doc._id, 1); }\n}",},
  'skiing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('skiing'))\n   {emit(doc._id, 1); }\n}",},
  'water polo': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('water polo'))\n   {emit(doc._id, 1); }\n}",},
  'volleyball': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('volleyball'))\n   {emit(doc._id, 1); }\n}",},
  'tennis': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('tennis'))\n   {emit(doc._id, 1); }\n}",},
  'team handball': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('team handball'))\n   {emit(doc._id, 1); }\n}",},
  'table tennis': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('table tennis'))\n   {emit(doc._id, 1); }\n}",},
  'swimming': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('swimming'))\n   {emit(doc._id, 1); }\n}",},
  'surfing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('surfing'))\n   {emit(doc._id, 1); }\n}",},
  'sprinting': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('sprinting'))\n   {emit(doc._id, 1); }\n}",},
  'skating': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('skating'))\n   {emit(doc._id, 1); }\n}",},
  'soccer': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('soccer'))\n   {emit(doc._id, 1); }\n}",},
  'skateboarding': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('skateboarding'))\n   {emit(doc._id, 1); }\n}",},
  'shooting': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('shooting'))\n   {emit(doc._id, 1); }\n}",},
  'rugby': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('rugby'))\n   {emit(doc._id, 1); }\n}",},
  'rowing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('rowing'))\n   {emit(doc._id, 1); }\n}",},
  'rodeo': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('rodeo'))\n   {emit(doc._id, 1); }\n}",},
  'racquetball': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('racquetball'))\n   {emit(doc._id, 1); }\n}",},
  'squash': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('squash'))\n   {emit(doc._id, 1); }\n}",},
  'pole vault': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('pole vault'))\n   {emit(doc._id, 1); }\n}",},
  'running': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('running'))\n   {emit(doc._id, 1); }\n}",},
  'martial arts': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('martial arts'))\n   {emit(doc._id, 1); }\n}",},
  'jumps': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('jumps'))\n   {emit(doc._id, 1); }\n}",},
  'lacrosse': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('lacrosse'))\n   {emit(doc._id, 1); }\n}",},
  'ice hockey': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('ice hockey'))\n   {emit(doc._id, 1); }\n}",},
  'jump': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('jump'))\n   {emit(doc._id, 1); }\n}",},
  'gymnastics': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('gymnastics'))\n   {emit(doc._id, 1); }\n}",},
  'golf': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('golf'))\n   {emit(doc._id, 1); }\n}",},
  'football': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('football'))\n   {emit(doc._id, 1); }\n}",},
  'fishing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('fishing'))\n   {emit(doc._id, 1); }\n}",},
  'field hockey': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('field hockey'))\n   {emit(doc._id, 1); }\n}",},
  'fencing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('fencing'))\n   {emit(doc._id, 1); }\n}",},
  'equestrian': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('equestrian'))\n   {emit(doc._id, 1); }\n}",},
  'diving': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('diving'))\n   {emit(doc._id, 1); }\n}",},
  'cycling': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('cycling'))\n   {emit(doc._id, 1); }\n}",},
  'curling': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('curling'))\n   {emit(doc._id, 1); }\n}",},
  'cheerleading': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('cheerleading'))\n   {emit(doc._id, 1); }\n}",},
  'canoe': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('canoe'))\n   {emit(doc._id, 1); }\n}",},
  'kayak': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('kayak'))\n   {emit(doc._id, 1); }\n}",},
  'bull': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('bull'))\n   {emit(doc._id, 1); }\n}",},
  'bareback': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('bareback'))\n   {emit(doc._id, 1); }\n}",},
  'bronc riding': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('bronc riding'))\n   {emit(doc._id, 1); }\n}",},
  'boxing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('boxing'))\n   {emit(doc._id, 1); }\n}",},
  'bowling': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('bowling'))\n   {emit(doc._id, 1); }\n}",},
  'bobsledding': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('bobsledding'))\n   {emit(doc._id, 1); }\n}",},
  'luge': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('luge'))\n   {emit(doc._id, 1); }\n}",},
  'billiards': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('billiards'))\n   {emit(doc._id, 1); }\n}",},
  'basketball': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('basketball'))\n   {emit(doc._id, 1); }\n}",},
  'baseball': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('baseball'))\n   {emit(doc._id, 1); }\n}",},
  'softball': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('softball'))\n   {emit(doc._id, 1); }\n}",},
  'badminton': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('badminton'))\n   {emit(doc._id, 1); }\n}",},
  'racing': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('racing'))\n   {emit(doc._id, 1); }\n}",},
  'archery': {'reduce': '_count',
   'map': "function (doc) {\n  if (doc.val.text.toLowerCase().includes('archery'))\n   {emit(doc._id, 1); }\n}",}},
 'language': 'javascript',
 'options': {'partitioned': True}}

couch.put('tweetdb/_design/sports', body=sports)